name: "Bug Report"
description: "Signaler un bug"
labels: [bug]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Merci de suivre le workflow Copilotage: l’issue crée la branche fix et sera liée au PR.
        
        - Branche: "fix/issue-<num>-<slug>"
  - Lors de l'ouverture de la PR: ajoutez les labels `prov:host=…`, `prov:pid=…`, `agent:GitHubCopilot`, `model=…`, `owner=…` (utilisez le script gh_pr_open.sh)
  - type: input
    id: summary
    attributes:
      label: Résumé
      description: Description courte du bug
      placeholder: Comportement attendu vs observé
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Étapes pour reproduire
      description: Détaillez les étapes et contextes
      placeholder: 1. … 2. … 3. …
    validations:
      required: true
  - type: input
    id: env
    attributes:
      label: Environnement
      placeholder: OS, Python, Navigateur, etc.
  - type: textarea
    id: logs
    attributes:
      label: Logs/erreurs
      render: shell
  - type: checkboxes
    id: checks
    attributes:
      label: Vérifications
      options:
        - label: J’ai recherché des issues similaires
        - label: J’ai fourni des étapes de reproduction claires
  - type: dropdown
    id: queue
    attributes:
      label: File (queue)
      options:
        - queue:backlog
        - queue:ready
        - queue:doing
        - queue:blocked
        - queue:done
    validations:
      required: false
  - type: dropdown
    id: priority
    attributes:
      label: Priorité
      options:
        - priority:low
        - priority:normal
        - priority:high
        - priority:urgent
    validations:
      required: false
  - type: dropdown
    id: size
    attributes:
      label: Taille estimée
      options:
        - size:XS
        - size:S
        - size:M
        - size:L
        - size:XL
    validations:
      required: false
