name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sanity
        run: |
          echo "Repo: $GITHUB_REPOSITORY"
          echo "SHA: $GITHUB_SHA"
          git ls-files | wc -l
